import React from "react";
import { motion } from "framer-motion";
import localFont from "@next/font/local";
const zigfont = localFont({ src: "../public/fonts/Inter-Regular.ttf" });
import { auth } from "./login/middleware/firebase";
import { signOut } from "firebase/auth";


type Props = {
  setAnswer: any;
  setInput: any;
};

const Footer = (props: Props) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 1, type: "spring", delay: 1 }}
      className={`${zigfont.className} z-20 bottom-3 left-0 right-0 sm:mx-1 flex flex-wrap flex-row justify-center space-x-4 sm:space-x-10 text-gray-400 absolute `}
    >
      <p
        className="hover:text-primary hover:scale-[1.05] hover:drop-shadow-2xl cursor-pointer "
        onClick={() => {
          props.setAnswer(
            `1-Type a question (ex- Buy a new car)\n\n2-Click Generate button \n\n5-Wait for response`
          );
          props.setInput("");
        }}
      >
        How to Use
      </p>
      <p
        className="hover:text-primary hover:scale-[1.05] hover:drop-shadow-2xl cursor-pointer"
        onClick={() => {
          props.setAnswer(
            "All the responses are generated by AI(ChatGPT Turbo-3.5).\nThe validity/accuracy of any response cant be guaranteed by us.\nThe use of Decision GPT is entirely at the user's own risk.\nWe will not be held liable for any damages or losses resulting from the use of this app, \nincluding but not limited to, direct, indirect, incidental, or consequential damages.\nBy using Decision GPT, you acknowledge and agree to these terms and conditions."
          );
          props.setInput("");
        }}
      >
        disclaimer
      </p>

      <p
        className="hover:text-primary hover:scale-[1.05] hover:drop-shadow-2xl cursor-pointer"
        onClick={() => {
          signOut(auth).then(() => {
            // Sign-out successful.
            localStorage.removeItem("email");
          }).catch((error) => {
            // An error happened.
          });
        }}
      >
        Logout
      </p>
      
    </motion.div>
  );
};

export default Footer;
